package com.kintone.client.app;

import static org.assertj.core.api.Assertions.assertThat;

import com.kintone.client.ApiTestBase;
import com.kintone.client.KintoneClient;
import com.kintone.client.TestSettings;
import com.kintone.client.api.app.*;
import com.kintone.client.helper.App;
import com.kintone.client.model.app.Device;
import com.kintone.client.model.app.View;
import com.kintone.client.model.app.ViewId;
import com.kintone.client.model.app.ViewType;
import java.util.*;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

/** AppClientのviews.jsonのテスト */
public class ViewsTest extends ApiTestBase {

    private static final String TEXT_FIELD_CODE = "文字列__1行_";
    private static final String NUMBER_FIELD_CODE = "数値";
    private static final String DATE_FIELD_CODE = "日付";

    private KintoneClient client;
    private App app;
    private Map<String, View> originalViews;

    @BeforeEach
    public void setupApp() {
        client = setupDefaultClient();
        Long testAppId = TestSettings.get().getTestAppId();
        if (testAppId != null) {
            app = App.fromExisting(client, testAppId);
        } else {
            throw new IllegalStateException(
                    "KINTONE_TEST_APP_ID is not set. Please create a test app and set the environment variable.");
        }
        // 元のビュー設定を保存
        originalViews = app.getViews(false);
    }

    @AfterEach
    public void cleanupViews() {
        if (app != null) {
            try {
                // 現在のビュー設定を取得して、自動生成ビューを保持しつつ元に戻す
                Map<String, View> currentViews = app.getViews(true);
                Map<String, View> viewsToRestore = new HashMap<>(originalViews);
                // プロセス管理で自動生成されるビュー（「（作業者が自分）」など）は削除不可なので保持
                for (Map.Entry<String, View> entry : currentViews.entrySet()) {
                    String name = entry.getKey();
                    if (name.startsWith("（") && name.endsWith("）")) {
                        viewsToRestore.put(name, entry.getValue());
                    }
                }
                client.app().updateViews(app.id(), viewsToRestore);
                client.app().deployApp(app.id());
                app.waitDeploy();
            } catch (Exception e) {
                // ignore cleanup errors
            }
        }
    }

    @Test
    public void getViews_getViewsPreview() {
        // 自動生成ビュー（プロセス管理）との重複を避けるため、index=100から開始
        View view =
                listView("v1", 100, "", NUMBER_FIELD_CODE + " asc", TEXT_FIELD_CODE, NUMBER_FIELD_CODE);
        // 自動生成ビューを保持しながら新しいビューを追加
        Map<String, View> viewsToUpdate = preserveAutoGeneratedViews(app.getViews(false));
        viewsToUpdate.put("v1", view);
        app.updateViews(viewsToUpdate).deploy();
        long revision = app.getAppRevision(false);

        GetViewsRequest req1 = new GetViewsRequest();
        req1.setApp(app.id());
        GetViewsResponseBody resp1 = client.app().getViews(req1);
        assertThat(resp1.getRevision()).isEqualTo(revision);
        Map<String, View> views = resp1.getViews();
        assertThat(views).containsKey("v1");
        // indexはkintoneによって正規化されるため、idとindexを無視して比較
        assertThat(views.get("v1"))
                .usingRecursiveComparison()
                .ignoringFieldsMatchingRegexes("id", "index")
                .isEqualTo(view);

        // 自動生成ビューとの重複を避けるため、index=101
        // LIST型のビューにはfieldsが必須
        View view2 =
                listView("v2", 101, "", NUMBER_FIELD_CODE + " asc", TEXT_FIELD_CODE, NUMBER_FIELD_CODE);
        Map<String, View> viewsToUpdate2 = preserveAutoGeneratedViews(app.getViews(true));
        viewsToUpdate2.put("v2", view2);
        app.updateViews(viewsToUpdate2);

        GetViewsPreviewRequest req2 = new GetViewsPreviewRequest();
        req2.setApp(app.id());
        GetViewsPreviewResponseBody resp2 = client.app().getViewsPreview(req2);
        assertThat(resp2.getRevision()).isEqualTo(revision + 1);
        views = resp2.getViews();
        assertThat(views).containsKey("v2");
        // indexはkintoneによって正規化されるため、idとindexを無視して比較
        assertThat(views.get("v2"))
                .usingRecursiveComparison()
                .ignoringFieldsMatchingRegexes("id", "index")
                .isEqualTo(view2);
    }

    @Test
    public void updateViews() {
        long revision = app.getAppRevision(true);

        // 自動生成ビューを保持しながら新しいビューを追加
        // 自動生成ビュー（プロセス管理）との重複を避けるため、index=100から開始
        Map<String, View> views = preserveAutoGeneratedViews(app.getViews(true));
        String sort = DATE_FIELD_CODE + " desc";
        views.put("v1", listView("v1", 100, "", sort, TEXT_FIELD_CODE));
        views.put("v2", calendarView("v2", 101, TEXT_FIELD_CODE, DATE_FIELD_CODE, "", sort));
        views.put("v3", customizeView("v3", 102, "test", "", sort));

        UpdateViewsRequest req = new UpdateViewsRequest();
        req.setApp(app.id());
        req.setRevision(revision);
        req.setViews(views);
        UpdateViewsResponseBody resp = client.app().updateViews(req);
        assertThat(resp.getRevision()).isEqualTo(revision + 1);
        assertThat(resp.getViews().get("v1").getId()).isGreaterThan(0);
        assertThat(resp.getViews().get("v2").getId()).isGreaterThan(0);
        assertThat(resp.getViews().get("v3").getId()).isGreaterThan(0);
        updateViewIds(views, resp.getViews());

        Map<String, View> settings = app.getViews(true);
        // indexはkintoneによって正規化されるため、indexを無視して比較
        assertThat(settings.get("v1"))
                .usingRecursiveComparison()
                .ignoringFields("index")
                .isEqualTo(views.get("v1"));
        assertThat(settings.get("v2"))
                .usingRecursiveComparison()
                .ignoringFields("index")
                .isEqualTo(views.get("v2"));
        assertThat(settings.get("v3"))
                .usingRecursiveComparison()
                .ignoringFields("index")
                .isEqualTo(views.get("v3"));
    }

    private void updateViewIds(Map<String, View> views, Map<String, ViewId> ids) {
        for (View view : views.values()) {
            ViewId viewId = ids.get(view.getName());
            if (viewId != null) {
                view.setId(viewId.getId());
            }
        }
    }

    private Map<String, View> preserveAutoGeneratedViews(Map<String, View> currentViews) {
        Map<String, View> result = new HashMap<>();
        for (Map.Entry<String, View> entry : currentViews.entrySet()) {
            String name = entry.getKey();
            if (name.startsWith("（") && name.endsWith("）")) {
                result.put(name, entry.getValue());
            }
        }
        return result;
    }

    private View listView(String name, long index, String query, String sort, String... fields) {
        View v = new View();
        v.setName(name);
        v.setType(ViewType.LIST);
        v.setIndex(index);
        v.setFields(Arrays.asList(fields));
        v.setFilterCond(query);
        v.setSort(sort);
        return v;
    }

    private View calendarView(
            String name, long index, String titleField, String dateField, String query, String sort) {
        View v = new View();
        v.setName(name);
        v.setType(ViewType.CALENDAR);
        v.setIndex(index);
        v.setTitle(titleField);
        v.setDate(dateField);
        v.setFilterCond(query);
        v.setSort(sort);
        return v;
    }

    private View customizeView(String name, long index, String html, String query, String sort) {
        View v = new View();
        v.setName(name);
        v.setType(ViewType.CUSTOM);
        v.setIndex(index);
        v.setHtml(html);
        v.setFilterCond(query);
        v.setSort(sort);
        v.setDevice(Device.ANY);
        v.setPager(true);
        return v;
    }
}
