plugins {
    id 'java'
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

repositories {
    mavenCentral()
}

dependencies {
    implementation project(':')

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.3'
    testImplementation 'org.assertj:assertj-core:3.26.0'

    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.3'
}

test {
    useJUnitPlatform()
    jvmArgs '-Duser.timezone=Asia/Tokyo'
}
