name: License

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  license-finder:
    name: License Finder

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 1.8
      uses: actions/setup-java@v4
      with:
        distribution: 'corretto'
        java-version: '8'
        cache: 'gradle'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Install License Finder
      run: sudo gem install license_finder
    - name: Check licenses
      run: license_finder --decisions-file=license-finder-decisions.yml
