auth_param basic program /usr/lib/squid/basic_ncsa_auth /var/squid/passwords
auth_param basic children 5
auth_param basic credentialsttl 1 minute
acl auth proxy_auth REQUIRED

acl SSL_ports port 443
acl Safe_ports port 80      # http
acl Safe_ports port 443     # https
acl CONNECT method CONNECT

http_access deny !Safe_ports
http_access deny CONNECT !SSL_ports
http_access allow localhost manager
http_access deny manager
http_access allow auth      # allow access with authentication
http_access deny all
http_port 3128
coredump_dir /var/spool/squid
refresh_pattern . 0 0% 0    # don't cache
request_entities on         # allow GET and HEAD requests with request entities
pid_filename /var/squid/squid.pid
logfile_rotate 0
cache_log stdio:/dev/stdout
access_log stdio:/dev/stdout
